spring:
#  datasource:
#    url: jdbc:h2:tcp://localhost/~/h2dbms
#    username: sa
#    password:
#   driver-class-name: org.h2.Driver

  datasource:
    url: jdbc:mysql://localhost:3306/smallshop?allowPublicKeyRetrieval=false&serverTimezone=Asia/Seoul
    username: test
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver # MySQL 드라이버 클래스

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
#        show_sql: true
        format_sql: true

logging.level:
  org.hibernate.SQL: debug
#  org.hibernate.type: trace